### ISSUE TITLE
Spot instances are not created

### ISSUE THREAD

**Issue by sai-tirunagiri** [RetailMeNotSandbox/ecs-selenium#12]
Hi,

Even after changing the instance types, not able to create spot instances. Is there any method that I should be following before creating the fleet.?

* I dont see any instances running in spot instances.
* in the history it says:
   allLaunchSpecsTemporarilyBlacklisted | Several attempts to launch instances have failed. Either the request could not be satisfied or the configuration is not valid. We will retry the request again later. For more information, see the description of the event.
-- | --

Is there a way, instead of spot instances, create just an instance - EC2 and run the containers in it.?

Please advice.

Thanks

**Comment by robertoriv** [comment]
It looks like your instance type and price combination might have not matched anything available for Spot. One thing to try is to go through the SpotFleet wizard, tell it the instance size you want and how many. It will tell you what bid price to put in. With that information you can update the `NodeInstanceType` and `MaxSpotBidPrice` parameters for the stack.

If you want to use regular EC2 instance, the README mentions that it is an option:

> An AutoScaling Group is also provided as fall-back; in case Spot Fleet doesn't fit your needs. All you need to do is scale it up.

The AutoScaling Group is created automatically for you. You just need to find it in the EC2 console, edit its settings (set its desired capacity to any number other than 0) and instances should come up.

**Comment by sharath-yml** [comment]
I had the same issue. I got it fixed after I increased the disk/volume size. Your selected AMI might require bigger volume size than specified. I am using Terraform though.

**Comment by robertoriv** [comment]
@sharath-yml thanks for the info. We used to run these in a "production" deployment with 22GB, but eventually upped the number to 100GB because the nodes were eating into the IOPS and the instances went unresponsive.

That's how this ended up as a parameter:
```
  DockerVolumeSize:
    Type: Number
    Default: 22
    Description: Size (in GiB) of the EBS volume that Docker users for image and metadata storage.  # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-storage-config.html
```

@sai-tirunagiri are you still having issues?
