### ISSUE TITLE
Help needed: Hub EC2 instance with public IP and NATed Node EC2 instances

### ISSUE THREAD

**Issue by manuelkiessling** [RetailMeNotSandbox/ecs-selenium#18]
There's something I'm not being able to wrap my head around. The CF spins up 1 "Hub" EC2 instance and `ECS_SELENIUM_DESIRED_FLEET_CAP` number of "Node" instances.

The Hub instance is configured to use a public IPv4 address (via `AssociatePublicIpAddress: true`), and the Node instances do not.

Here's the catch I'm running into: I've created a VPC for the Stack, and in this VPC, I've created two subnets. These are the subnets which I provide via `ECS_SELENIUM_SUBNET_IDS`, thus all instances, Hub and Node(s), are attached to this subnet.

Now, there are two ways to configure these subnets in terms of routing:

a) I create two NAT Gateways, and define routing tables for the subnets which route all `0.0.0.0/0` traffic through these NAT Gateways - this makes the subnets "private"; it allows the Hub and all Nodes to reach the public internet, but I cannot reach the Hub on its public IP from the outside, only via another instance within the VPC (thus rendering the public IP assignment for the Hub somewhat useless).

b) I do not create NAT Gateways, but instead define routing tables for the subnets which route all `0.0.0.0/0` traffic through the Internet Gateway of my VPC - this makes the subnets "public"; it allows me to reach the Hub on its public IP from the outside and allows the Hub to reach the public Internet; however, the lack of NAT Gateways results in the Node instances not being able to reach the public internet (and as a result, the Stack cannot be fully created, because the Node instances need public internet access e.g. to do their `yum` installs).

What is it that I'm not getting here?

**Comment by rrivera-rmn** [comment]
@manuelkiessling, you are right. In our current deployment we are VPNed into the VPC, so we use the internal IP (and private subnets).

If that doesn't work for your use-case, you could add an extra subnet parameter for a public subnet, and make the ELB external:

```yaml
Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  PrivateSubnetIds:  # changed name
    Type: List<String>
    Description: A comma-delimitted list of (private) SubnetIds in your Virtual Private Cloud (VPC)
  PublicSubnetIds:  # added
    Type: List<String>
    Description: A comma-delimitted list of (public) SubnetIds in your Virtual Private Cloud (VPC)

...

  HubLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      SecurityGroups:
      - !Ref HubLoadBalancerSecurityGroup
      Subnets: !Ref PublicSubnetIds
```

You may also want to make the Hosted Zone public, to resolve names from outside the VPC.

(I haven't tested this. Just throwing out some ideas.)
